
import {
  Book,
  Brain,
  PenTool,
  Globe,
  Palette,
  Dumbbell,
  Music,
  Laptop,
  MessageSquare,
  Briefcase,
  GraduationCap,
  Megaphone,
  ShoppingCart,
  Search,
  TrendingUp,
  Mail,
  Smile,
  Monitor,
  FlaskConical,
  HeartPulse,
  MessageCircle,
  Leaf,
  Users,
  Library,
  Lightbulb,
  Home,
  Cpu,
  Drama,
  DollarSign,
  Globe2,
  Camera,
  Languages,
  DramaIcon,
  UserCheck,
  Bot,
  Headphones,
  Landmark,
  ScrollText,
  Gavel,
  Cog,
  BookOpen,
  BrainCog,
  Database,
  Scale,
  Activity,
  ClipboardCheck,
  BarChart3,
  Layout,
  Edit3,
  User,
  ShieldCheck,
  Store,
  Calculator,
  Package,
  Video,
  Lock,
} from "lucide-react"

export const subjectData = {
  elementary: [
    { name: "Language Arts", icon: Book, progress: 100 },
    { name: "Mathematics", icon: Brain, progress: 100 },
    { name: "Science", icon: FlaskConical, progress: 100 },
    { name: "Social Studies", icon: Globe, progress: 100 },
    { name: "Art", icon: Palette, progress: 100 },
    { name: "Music", icon: Music, progress: 100 },
    { name: "PE", icon: Dumbbell, progress: 100 },
    { name: "Technology", icon: Laptop, progress: 100 },
    { name: "Health", icon: HeartPulse, progress: 100 },
    { name: "World Languages", icon: MessageCircle, progress: 100 },
    { name: "Character Education", icon: Users, progress: 100 },
    { name: "Environmental Education", icon: Leaf, progress: 100 },
    { name: "Library Media", icon: Library, progress: 100 },
    { name: "Life Skills", icon: Lightbulb, progress: 100 },
    { name: "Social Emotional Learning", icon: Smile, progress: 100 },
  ],

  middle: [
    { name: "Language Arts", icon: Book, progress: 100 },
    { name: "Mathematics", icon: Brain, progress: 100 },
    { name: "Science", icon: FlaskConical, progress: 100 },
    { name: "Social Studies", icon: Globe, progress: 100 },
    { name: "Art", icon: Palette, progress: 100 },
    { name: "Music", icon: Music, progress: 100 },
    { name: "PE", icon: Dumbbell, progress: 100 },
    { name: "Technology", icon: Laptop, progress: 100 },
    { name: "Health Education", icon: HeartPulse, progress: 100 },
    { name: "World Languages", icon: MessageCircle, progress: 100 },
    { name: "Family and Consumer Science", icon: Home, progress: 100 },
    { name: "Technology Education and Engineering", icon: Cpu, progress: 100 },
    { name: "Environmental Studies", icon: Leaf, progress: 100 },
    { name: "Drama and Theatre", icon: Drama, progress: 100 },
    { name: "Career Exploration", icon: Briefcase, progress: 100 },
    { name: "Social Emotional Learning", icon: Smile, progress: 100 },
    { name: "Digital Literacy", icon: Monitor, progress: 100 },
  ],

  high: [
    { name: "Language Arts", icon: Book, progress: 100 },
    { name: "Mathematics", icon: Brain, progress: 100 },
    { name: "Science", icon: FlaskConical, progress: 100 },
    { name: "Social Studies", icon: Globe, progress: 100 },
    { name: "Art", icon: Palette, progress: 100 },
    { name: "Music", icon: Music, progress: 100 },
    { name: "PE", icon: Dumbbell, progress: 100 },
    { name: "Technology", icon: Laptop, progress: 100 },
    { name: "Health Education", icon: HeartPulse, progress: 100 },
    { name: "World Languages", icon: MessageSquare, progress: 100 },
    { name: "Business Education", icon: DollarSign, progress: 100 },
    { name: "Engineering and Technology", icon: Cpu, progress: 100 },
    { name: "Environmental Studies", icon: Leaf, progress: 100 },
    { name: "World Languages and Cultures", icon: Globe2, progress: 100 },
    { name: "Social Emotional Learning", icon: Smile, progress: 100 },
    { name: "Digital Media and Communications", icon: Camera, progress: 100 },
    { name: "Family and Consumer Sciences", icon: Home, progress: 100 },
    { name: "Psychology and Sociology", icon: Users, progress: 100 },
  ],

  international: [
    { name: "Language Arts", icon: Book, progress: 100 },
    { name: "Mathematics", icon: Brain, progress: 100 },
    { name: "Science", icon: FlaskConical, progress: 100 },
    { name: "Social Studies", icon: Globe, progress: 100 },
    { name: "Art", icon: Palette, progress: 100 },
    { name: "Music", icon: Music, progress: 100 },
    { name: "Physical Education", icon: Dumbbell, progress: 100 },
    { name: "Technology", icon: Laptop, progress: 100 },
    { name: "Global Studies", icon: Globe2, progress: 100 },
    // { name: "World Languages", icon: MessageSquare, progress: 100 },
    { name: "Environmental Education", icon: Leaf, progress: 100 },
    { name: "Technology and Engineering", icon: Cpu, progress: 100 },
    { name: "Business Education", icon: Briefcase, progress: 100 },
    { name: "Information Technology", icon: Monitor, progress: 100 },
    { name: "Health and Wellness", icon: HeartPulse, progress: 100 },
    { name: "World Languages", icon: Languages, progress: 100 },
    { name: "Drama and Theater Arts", icon: DramaIcon, progress: 100 },
    { name: "Digital Media and Communication", icon: Camera, progress: 100 },
    { name: "Life Skills Career Preparation", icon: UserCheck, progress: 100 },
  ],

  undergraduate: [
    // { name: "AI and ML", icon: Bot, progress: 100 },
    { name: "Humanities", icon: Globe, progress: 100 },
    { name: "Business", icon: Briefcase, progress: 100 },
    { name: "Art and Design", icon: Palette, progress: 100 },
    { name: "Health and Medicine", icon: HeartPulse, progress: 100 },
    { name: "Language and Literature", icon: Book, progress: 100 },
    { name: "Music Composition", icon: Music, progress: 100 },
    { name: "Advanced Mathematics", icon: Brain, progress: 100 },
    { name: "Engineering", icon: Cpu, progress: 100 },
    { name: "Computer Science", icon: Laptop, progress: 100 },
    { name: "Economics", icon: DollarSign, progress: 100 },
    { name: "Environmental Science", icon: Leaf, progress: 100 },
    { name: "Psychology", icon: Headphones, progress: 100 },
    { name: "Political Science", icon: Landmark, progress: 100 },
    { name: "Communications and Media", icon: Camera, progress: 100 },
    { name: "Education", icon: GraduationCap, progress: 100 },
    { name: "Sociology", icon: Users, progress: 100 },
    { name: "History", icon: ScrollText, progress: 100 },
    { name: "Law and Legal Studies", icon: Gavel, progress: 100 },
  ],

  graduate: [
    { name: "AI and ML", icon: Cpu, progress: 100 },
    { name: "Engineering Research", icon: Cog, progress: 100 },
    { name: "Advanced Business Management", icon: Briefcase, progress: 100 },
    { name: "Health and Medicine", icon: HeartPulse, progress: 100 },
    { name: "Social Sciences", icon: Users, progress: 100 },
    { name: "Literature and Critical Theory", icon: BookOpen, progress: 100 },
    { name: "Art and Design", icon: Palette, progress: 100 },
    { name: "Educational Leadership", icon: GraduationCap, progress: 100 },
    { name: "Data Science and Analytics", icon: Database, progress: 100 },
    { name: "Environmental Studies and Sustainability", icon: Leaf, progress: 100 },
    { name: "Computer Science", icon: Laptop, progress: 100 },
    { name: "Public Administration and Policy", icon: Landmark, progress: 100 },
    { name: "Law and Legal Studies", icon: Gavel, progress: 100 },
    { name: "Economics", icon: DollarSign, progress: 100 },
    { name: "Psychology and Counseling", icon: BrainCog, progress: 100 },
    { name: "Communications and Media Studies", icon: MessageSquare, progress: 100 },
    { name: "History and Advanced Studies", icon: ScrollText, progress: 100 },
    { name: "Public Health", icon: Activity, progress: 100 },
    { name: "Philosophy and Ethics", icon: Scale, progress: 100 },
  ],

  nonStudent: [
    { name: "Digital Marketing", icon: Megaphone, progress: 100 },
    { name: "SEO Specialist", icon: Search, progress: 100 },
    { name: "E Commerce Dropshipping", icon: ShoppingCart, progress: 100 },
    { name: "Stock Market Investment", icon: TrendingUp, progress: 100 },
    { name: "Email Writing Business Communication", icon: Mail, progress: 100 },
    { name: "Project Management", icon: ClipboardCheck, progress: 100 },
    { name: "Data Analytics", icon: BarChart3, progress: 100 },
    { name: "UX UI Design", icon: Layout, progress: 100 },
    { name: "Copywriting Content Creation", icon: Edit3, progress: 100 },
    { name: "Personal Branding", icon: User, progress: 100 },
    { name: "Real Estate Investment", icon: Home, progress: 100 },
    { name: "Cybersecurity", icon: ShieldCheck, progress: 100 },
    { name: "Entrepreneurship", icon: Store, progress: 100 },
    { name: "Human Resources", icon: Users, progress: 100 },
    { name: "Sales Business Development", icon: DollarSign, progress: 100 },
    { name: "Financial Management", icon: Calculator, progress: 100 },
    { name: "Cybersecurity Compliance", icon: Lock, progress: 100 },
    { name: "Product Management", icon: Package, progress: 100 },
    { name: "Graphic Design Branding", icon: PenTool, progress: 100 },
    { name: "Video Film Production", icon: Video, progress: 100 },
    { name: "Leadership Executive Coaching", icon: Briefcase, progress: 100 },
  ],
}

 
const allSubjectNames = Object.values(subjectData).flatMap(category => 
  category.map(subject => subject.name)
); 
export {allSubjectNames}